### ISSUE TITLE
Implement API

### ISSUE THREAD

**Issue by gtema** [stackmon/status-dashboard#13]
API for creating incidents

- POST /incident (create new incident for component by name and attributes)
```
{
  component: "examle_comp", 
  component_attributes: [
     {
      name: "region",
      value: "eu-de"
     }
  ]
  impact: 2
}
```

- GET /incidents (get list of open incidents)

**Comment by bakhterets** [comment]
need to add:
1. component (name,attribute) search
2. check active incidents:
    1) check active "maintenance (for component): if True > pass;
    2) if non maintenance > search affected components: if component in affected > pass; else > update incident (affected components)
    3) create new incident

need to add new func to Incident(Model):
get_active_maintenance
get_active_incident



## for component (end_date == None) (start_date < current_date)

change Name of API to post components state

POST /components_status

**Comment by gtema** [comment]
Done
