### ISSUE TITLE
Implement RSS feed

### ISSUE THREAD

**Issue by gtema** [stackmon/status-dashboard#14]
RSS feed in a backwards compatible way (like on https://status.otc-service.com/) must be implemented:

- https://status.otc-service.com/rss/?mt=Europe%20%28Germany%29
- https://status.otc-service.com/rss/?mt=Europe%20%28Netherlands%29
- https://status.otc-service.com/rss/?mt=%20Global%20Services
- https://status.otc-service.com/rss/?mt=Europe%20%28Germany%29&srvc=Access%20to%20the%20GUI&srv=Enterprise%20Dashboard
- ...

mt => region
srvc => service category, but can be simply ignored (must be supported as param though)
srv => component name

In addition to the backward compatible feed there should be a normal implementation with a path based parameterization (/rss/:region)

**Comment by bakhterets** [comment]
Done
