### ISSUE TITLE
Auth with missing group membership leads to 500 error

### ISSUE THREAD

**Issue by gtema** [stackmon/status-dashboard#27]
Auth of user through openid without group membership causes browser to show "internal server error", while from app pov everything is fine. This hints that response is not correct

**Comment by gtema** [comment]
This turned out to be an issue with authlib that fails to validate the CSRF token:

authlib.integrations.base_client.errors.MismatchingStateError: mismatching_state: CSRF Warning! State not equal in request and response.

**Comment by bakhterets** [comment]
I think the problem is that gunicorn mixes sessions between workers.
When I use -w 1 parameter the problem is not reproducing.

**Comment by bakhterets** [comment]
This is not a bug, this is a feature of how WSGI works.

**Comment by bakhterets** [comment]
The principle of operation of "Gunicorn" does not imply a solution to this problem.
Gunicorn doesn't support sticky sessions.
